# Generated by Django 3.2.6 on 2021-08-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid_vaccine_statewise_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UpdatedOn', models.TextField()),
                ('State', models.TextField()),
                ('total_doses_adminstered', models.TextField()),
                ('Total_Sessions_Conducted', models.TextField()),
                ('Total_Sites', models.TextField()),
                ('First_Dose_Administered', models.TextField()),
                ('Second_Dose_Administered', models.TextField()),
                ('Male_Vaccinated', models.TextField()),
                ('Female_Vaccinated', models.TextField()),
                ('Transgender_Vaccinated', models.TextField()),
                ('Total_Covaxin_Administered', models.TextField()),
                ('Total_CoviShield_Administered', models.TextField()),
                ('Total_Sputnik_Administered', models.TextField()),
                ('AEFI', models.TextField()),
                ('age_18_45', models.TextField()),
                ('age_60_plus', models.TextField()),
                ('age_45_60', models.TextField()),
                ('Total_Individuals_Vaccinated', models.TextField()),
            ],
            options={
                'db_table': 'covid_statewise',
            },
        ),
    ]
