# Generated by Django 3.2.6 on 2021-08-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='AEFI',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='Female_Vaccinated',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='First_Dose_Administered',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='Male_Vaccinated',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='Second_Dose_Administered',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='State',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='Total_Covaxin_Administered',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='Total_CoviShield_Administered',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='Total_Individuals_Vaccinated',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='Total_Sessions_Conducted',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='Total_Sites',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='Total_Sputnik_Administered',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='Transgender_Vaccinated',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='UpdatedOn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='age_18_45',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='age_45_60',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='age_60_plus',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covid_vaccine_statewise_mode',
            name='total_doses_adminstered',
            field=models.TextField(null=True),
        ),
    ]
