# Generated by Django 3.2.6 on 2021-08-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210810_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='covid_india',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.TextField(null=True)),
                ('Date', models.TextField(null=True)),
                ('Time', models.TextField(null=True)),
                ('State_UnionTerritory', models.TextField(null=True)),
                ('ConfirmedIndianNational', models.TextField(null=True)),
                ('ConfirmedForeignNational', models.TextField(null=True)),
                ('Cured', models.TextField(null=True)),
                ('Deaths', models.TextField(null=True)),
                ('Confirmed', models.TextField(null=True)),
            ],
            options={
                'db_table': 'covid_india',
            },
        ),
        migrations.CreateModel(
            name='statewise_testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.TextField(null=True)),
                ('State', models.TextField(null=True)),
                ('TotalSamples', models.TextField(null=True)),
                ('Negative', models.TextField(null=True)),
                ('Positive', models.TextField(null=True)),
            ],
            options={
                'db_table': 'statewise_test',
            },
        ),
    ]
