# Generated by Django 3.2.6 on 2021-08-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_remove_covid_india_sno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covid_india',
            old_name='State_UnionTerritory',
            new_name='State',
        ),
    ]
